config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get("/", to: "bill_splitter#index", as: :root)

  post('/bill/process', to: "bill_splitter#process_bill", as: :process_bill)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bill_splitter_controller.rb
class BillSplitterController < ApplicationController

    def index
        render :bill
    end

    def process_bill
        @total = params[:total].to_f
        @taxes = params[:taxes].to_f
        @tip = params[:tip].to_f
        @people = params[:people].to_f
        
        
        @perperson = "Here is the answer "
    

        render :bill
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bill_splitter/bill.html.erb
<h1>This is my bill</h1>

<%= form_tag(process_bill_path) do %>
<div>
    <%= label_tag(:total) %> <br>
    <%= number_field_tag(:quantity) %>

</div>

<div>
    <%= label_tag(:taxes) %> <br>
    <%= number_field_tag(:taxes) %>
</div>


<div>

    <%= label_tag(:tip) %> <br>
    <%= number_field_tag(:tip) %>

</div>

<div>
    <%= label_tag(:people) %> <br>
    <%= number_field_tag(:people) %>

</div>


<%= submit_tag("calculate") %>

<div>
    <% if @perperson %>
        <%= @perperson %>
    <% end %> 

</div>

<% end %>

app/views/bill_splitter/results.html.erb
<p>
    Here is your <%= @total %>, the taxes equaled up to <%= @taxes %>,
    you should tip your waiter/waitress <%= @tip %> as you had <%= @people %>
    of people.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PayYourBill</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>